name: upenn-cis194
version: 0.1.0.0
github: "githubuser/upenn-cis194"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
    - README.md
    - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/upenn-cis194#readme>

default-extensions:
    - OverloadedStrings

dependencies:
    - base >= 4.8 && < 4.11
    - codeworld-api == 0.2.0.0

library:
    source-dirs: src

executables:
    upenn-cis194-exe:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - upenn-cis194

tests:
    upenn-cis194-test:
        main: Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - upenn-cis194
